packageExtensions:
  eslint-config-oclif@*:
    dependencies:
      eslint-plugin-unicorn: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-3.2.0-rc.13.cjs
